# Here you can put common things that will be used in the default image and the nvidia image

modules:

  - type: files
    files:
      #- homedir: /usr/etc/skel # homedir must have a non-hidden folder or so that the recipe can copy
      - usr: /usr # copy static configurations
                  # configuration you wish to end up in /etc/ on the booted system should be
                  # added into /usr/etc/ as that is the proper "distro" config directory on ostree
                  # read more in the files module's README

  - from-file: modules_config/packages.yml
  - from-file: modules_config/bling.yml
  - from-file: modules_config/yafti.yml
  #- from-file: modules_config/fonts.yml
  - from-file: modules_config/scripts.yml
  - from-file: modules_config/systemd.yml
